# OpenAI API Configuration
openai_model: "gpt-4o"
max_tokens: 600
confidence_threshold: 0.7

# Image Processing Settings
max_image_size: 2048
image_quality: 90

# Database Configuration
database:
  file_path: "site_violations.db"
  max_connections: 5

# Logging Configuration
logging:
  level: "INFO"
  max_file_size: 10485760  # 10MB
  backup_count: 5

# Safety Violation Detection Rules
violation_rules:
  high_risk:
    - no_hardhat: true
    - no_hi_vis: true
  medium_risk:
    - partial_ppe: true

# API Rate Limiting
rate_limiting:
  requests_per_minute: 20
  batch_processing_delay: 0.5  # seconds

# Security Settings
security:
  allowed_image_extensions: 
    - jpg
    - jpeg
    - png
    - gif
  max_image_size_mb: 5